// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrionPos.DataAccess.Context;

#nullable disable

namespace OrionPos.DataAccess.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    partial class DirectoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OrionPos.Entity.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f03f1a16-527e-4baf-a751-9e08dae53fe7",
                            Email = "user1@user.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Kullanıcı 1",
                            NormalizedEmail = "USER1@USER.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEF9rd8g+NbMaWSDWfZk93cowm9GtQ6fG6NnBbBQI3uS+TxQBxjckr6Zoic3aBKtHzQ==",
                            PhoneNumber = "0543 812 36 80",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a2fd5fa-37d3-4bae-b1d4-b50459effc7c",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdc909c3-bd74-4d87-b177-8954852aa3b2",
                            Email = "user2@user.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Kullanıcı 2",
                            NormalizedEmail = "USER2@USER.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEEJnMdeo9vO+jYnPxLt0+67NcV8cMiVLQnKOLPk5K2vCWd//Z7NUhRNy2vrSN4wA6g==",
                            PhoneNumber = "0543 812 36 81",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "20f0e749-9045-4e1c-b2d4-5334e0317366",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        });
                });

            modelBuilder.Entity("OrionPos.Entity.Entities.TelephoneDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUserId");

                    b.ToTable("telephoneDirectories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2023, 6, 4, 16, 38, 33, 716, DateTimeKind.Local).AddTicks(982),
                            CreatedUserId = 2,
                            FirstName = "Kerime",
                            IsDeleted = false,
                            LastName = "Aydoğan Yozgat",
                            TelephoneNumber = "530 307 08 92"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2023, 9, 17, 11, 22, 31, 190, DateTimeKind.Local).AddTicks(8374),
                            CreatedUserId = 1,
                            FirstName = "Hami",
                            IsDeleted = false,
                            LastName = "Aydoğdu",
                            TelephoneNumber = "534 955 16 09"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2023, 8, 7, 12, 46, 32, 649, DateTimeKind.Local).AddTicks(3682),
                            CreatedUserId = 2,
                            FirstName = "Thomas",
                            IsDeleted = false,
                            LastName = "Aygen",
                            TelephoneNumber = "533 782 40 15"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2023, 11, 7, 15, 55, 8, 543, DateTimeKind.Local).AddTicks(4902),
                            CreatedUserId = 1,
                            FirstName = "Güneş",
                            IsDeleted = false,
                            LastName = "Aykan",
                            TelephoneNumber = "546 350 55 98"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDateTime = new DateTime(2023, 9, 7, 16, 3, 12, 585, DateTimeKind.Local).AddTicks(2867),
                            CreatedUserId = 2,
                            FirstName = "Elif Feyza",
                            IsDeleted = false,
                            LastName = "Ayrım",
                            TelephoneNumber = "540 494 24 33"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDateTime = new DateTime(2023, 4, 5, 18, 42, 57, 841, DateTimeKind.Local).AddTicks(9405),
                            CreatedUserId = 1,
                            FirstName = "Uğur Ali",
                            IsDeleted = false,
                            LastName = "Aysal",
                            TelephoneNumber = "548 817 28 53"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDateTime = new DateTime(2023, 3, 5, 7, 58, 46, 201, DateTimeKind.Local).AddTicks(9823),
                            CreatedUserId = 2,
                            FirstName = "Osman Yasin",
                            IsDeleted = false,
                            LastName = "Aysan",
                            TelephoneNumber = "547 431 04 60"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDateTime = new DateTime(2023, 4, 16, 0, 5, 29, 683, DateTimeKind.Local).AddTicks(6724),
                            CreatedUserId = 1,
                            FirstName = "Adem",
                            IsDeleted = false,
                            LastName = "Ayvacık",
                            TelephoneNumber = "541 579 92 52"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDateTime = new DateTime(2023, 11, 8, 7, 34, 21, 593, DateTimeKind.Local).AddTicks(3019),
                            CreatedUserId = 2,
                            FirstName = "Sera Cansın",
                            IsDeleted = false,
                            LastName = "Azbay",
                            TelephoneNumber = "538 381 91 18"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDateTime = new DateTime(2023, 6, 16, 19, 13, 25, 224, DateTimeKind.Local).AddTicks(7790),
                            CreatedUserId = 1,
                            FirstName = "Ali İsmail",
                            IsDeleted = false,
                            LastName = "Babacan",
                            TelephoneNumber = "543 578 19 47"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDateTime = new DateTime(2023, 2, 5, 10, 50, 54, 219, DateTimeKind.Local).AddTicks(9713),
                            CreatedUserId = 2,
                            FirstName = "Ruhugül",
                            IsDeleted = false,
                            LastName = "Babadostu",
                            TelephoneNumber = "548 180 60 72"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDateTime = new DateTime(2023, 2, 4, 9, 16, 6, 921, DateTimeKind.Local).AddTicks(4920),
                            CreatedUserId = 1,
                            FirstName = "Alçiçek",
                            IsDeleted = false,
                            LastName = "Bad",
                            TelephoneNumber = "541 631 26 74"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDateTime = new DateTime(2023, 10, 1, 15, 27, 12, 42, DateTimeKind.Local).AddTicks(1930),
                            CreatedUserId = 2,
                            FirstName = "Memet",
                            IsDeleted = false,
                            LastName = "Bağcı",
                            TelephoneNumber = "531 167 67 76"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDateTime = new DateTime(2023, 10, 14, 8, 34, 28, 805, DateTimeKind.Local).AddTicks(8209),
                            CreatedUserId = 1,
                            FirstName = "Mercan",
                            IsDeleted = false,
                            LastName = "Bağçivan",
                            TelephoneNumber = "533 465 65 16"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDateTime = new DateTime(2022, 12, 23, 10, 57, 2, 173, DateTimeKind.Local).AddTicks(6726),
                            CreatedUserId = 2,
                            FirstName = "Gökay",
                            IsDeleted = false,
                            LastName = "Bağış",
                            TelephoneNumber = "533 592 75 55"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDateTime = new DateTime(2023, 7, 14, 12, 55, 24, 518, DateTimeKind.Local).AddTicks(4537),
                            CreatedUserId = 1,
                            FirstName = "Pırıltı",
                            IsDeleted = false,
                            LastName = "Bahçeli",
                            TelephoneNumber = "536 856 62 00"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDateTime = new DateTime(2023, 11, 2, 8, 0, 32, 715, DateTimeKind.Local).AddTicks(7915),
                            CreatedUserId = 2,
                            FirstName = "Özgün",
                            IsDeleted = false,
                            LastName = "Bahtıyar",
                            TelephoneNumber = "535 178 99 84"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDateTime = new DateTime(2023, 1, 23, 19, 46, 52, 564, DateTimeKind.Local).AddTicks(5979),
                            CreatedUserId = 1,
                            FirstName = "Özgen",
                            IsDeleted = false,
                            LastName = "Baka",
                            TelephoneNumber = "541 556 39 38"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDateTime = new DateTime(2023, 11, 6, 16, 49, 17, 338, DateTimeKind.Local).AddTicks(7076),
                            CreatedUserId = 2,
                            FirstName = "Seung Hun",
                            IsDeleted = false,
                            LastName = "Baki",
                            TelephoneNumber = "543 519 67 24"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDateTime = new DateTime(2023, 5, 3, 21, 57, 45, 822, DateTimeKind.Local).AddTicks(2033),
                            CreatedUserId = 1,
                            FirstName = "Gülser",
                            IsDeleted = false,
                            LastName = "Bal",
                            TelephoneNumber = "541 215 21 00"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDateTime = new DateTime(2023, 11, 10, 11, 34, 10, 302, DateTimeKind.Local).AddTicks(364),
                            CreatedUserId = 2,
                            FirstName = "Yüksel",
                            IsDeleted = false,
                            LastName = "Balcı",
                            TelephoneNumber = "539 712 93 55"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDateTime = new DateTime(2023, 11, 21, 21, 57, 8, 994, DateTimeKind.Local).AddTicks(850),
                            CreatedUserId = 1,
                            FirstName = "Ecren",
                            IsDeleted = false,
                            LastName = "Baldo",
                            TelephoneNumber = "531 831 79 52"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDateTime = new DateTime(2023, 5, 13, 18, 48, 47, 875, DateTimeKind.Local).AddTicks(6390),
                            CreatedUserId = 2,
                            FirstName = "Muhammet Raşit",
                            IsDeleted = false,
                            LastName = "Balı",
                            TelephoneNumber = "534 600 55 51"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDateTime = new DateTime(2023, 2, 13, 16, 0, 30, 771, DateTimeKind.Local).AddTicks(896),
                            CreatedUserId = 1,
                            FirstName = "Sakıp",
                            IsDeleted = false,
                            LastName = "Balıoğlu",
                            TelephoneNumber = "541 641 99 20"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDateTime = new DateTime(2023, 9, 9, 7, 34, 14, 525, DateTimeKind.Local).AddTicks(7227),
                            CreatedUserId = 2,
                            FirstName = "Kazım",
                            IsDeleted = false,
                            LastName = "Balta",
                            TelephoneNumber = "549 594 36 36"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDateTime = new DateTime(2023, 7, 19, 23, 14, 3, 778, DateTimeKind.Local).AddTicks(2321),
                            CreatedUserId = 1,
                            FirstName = "Abdullah Atakan",
                            IsDeleted = false,
                            LastName = "Baluken",
                            TelephoneNumber = "533 279 66 32"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDateTime = new DateTime(2023, 1, 24, 10, 7, 13, 714, DateTimeKind.Local).AddTicks(5890),
                            CreatedUserId = 2,
                            FirstName = "Coşkun",
                            IsDeleted = false,
                            LastName = "Baran",
                            TelephoneNumber = "538 343 73 88"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDateTime = new DateTime(2023, 5, 12, 5, 39, 24, 570, DateTimeKind.Local).AddTicks(2853),
                            CreatedUserId = 1,
                            FirstName = "Serdar Kaan",
                            IsDeleted = false,
                            LastName = "Barbaros",
                            TelephoneNumber = "534 192 65 99"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDateTime = new DateTime(2023, 1, 9, 7, 28, 13, 275, DateTimeKind.Local).AddTicks(1295),
                            CreatedUserId = 2,
                            FirstName = "Ezel",
                            IsDeleted = false,
                            LastName = "Bargan",
                            TelephoneNumber = "540 107 21 17"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDateTime = new DateTime(2023, 11, 21, 16, 9, 54, 590, DateTimeKind.Local).AddTicks(1213),
                            CreatedUserId = 1,
                            FirstName = "Ayşegül",
                            IsDeleted = false,
                            LastName = "Barutçuoğlu",
                            TelephoneNumber = "544 487 33 21"
                        },
                        new
                        {
                            Id = 31,
                            CreatedDateTime = new DateTime(2023, 5, 8, 8, 46, 18, 833, DateTimeKind.Local).AddTicks(9002),
                            CreatedUserId = 2,
                            FirstName = "Sefa Kadir",
                            IsDeleted = false,
                            LastName = "Başar",
                            TelephoneNumber = "534 324 17 99"
                        },
                        new
                        {
                            Id = 32,
                            CreatedDateTime = new DateTime(2023, 12, 1, 15, 8, 46, 472, DateTimeKind.Local).AddTicks(5851),
                            CreatedUserId = 1,
                            FirstName = "Elif Etga",
                            IsDeleted = false,
                            LastName = "Başeğmez",
                            TelephoneNumber = "537 619 30 62"
                        },
                        new
                        {
                            Id = 33,
                            CreatedDateTime = new DateTime(2023, 12, 3, 10, 52, 16, 244, DateTimeKind.Local).AddTicks(5488),
                            CreatedUserId = 2,
                            FirstName = "Balın",
                            IsDeleted = false,
                            LastName = "Baştepe",
                            TelephoneNumber = "549 448 37 12"
                        },
                        new
                        {
                            Id = 34,
                            CreatedDateTime = new DateTime(2023, 2, 14, 7, 28, 37, 360, DateTimeKind.Local).AddTicks(1108),
                            CreatedUserId = 1,
                            FirstName = "Mahperi",
                            IsDeleted = false,
                            LastName = "Baştopçu",
                            TelephoneNumber = "546 268 83 09"
                        },
                        new
                        {
                            Id = 35,
                            CreatedDateTime = new DateTime(2023, 9, 4, 7, 33, 34, 572, DateTimeKind.Local).AddTicks(3384),
                            CreatedUserId = 2,
                            FirstName = "Erol Özgür",
                            IsDeleted = false,
                            LastName = "Baştuğ",
                            TelephoneNumber = "537 810 63 52"
                        },
                        new
                        {
                            Id = 36,
                            CreatedDateTime = new DateTime(2023, 10, 16, 23, 47, 36, 367, DateTimeKind.Local).AddTicks(1630),
                            CreatedUserId = 1,
                            FirstName = "Atak",
                            IsDeleted = false,
                            LastName = "Batar",
                            TelephoneNumber = "550 479 16 22"
                        },
                        new
                        {
                            Id = 37,
                            CreatedDateTime = new DateTime(2023, 10, 16, 5, 46, 28, 795, DateTimeKind.Local).AddTicks(8362),
                            CreatedUserId = 2,
                            FirstName = "Safa",
                            IsDeleted = false,
                            LastName = "Batga",
                            TelephoneNumber = "547 623 44 35"
                        },
                        new
                        {
                            Id = 38,
                            CreatedDateTime = new DateTime(2023, 5, 26, 16, 30, 7, 760, DateTimeKind.Local).AddTicks(3386),
                            CreatedUserId = 1,
                            FirstName = "Gökmen",
                            IsDeleted = false,
                            LastName = "Battal",
                            TelephoneNumber = "533 193 99 52"
                        },
                        new
                        {
                            Id = 39,
                            CreatedDateTime = new DateTime(2023, 9, 23, 19, 51, 14, 591, DateTimeKind.Local).AddTicks(2467),
                            CreatedUserId = 2,
                            FirstName = "Fazıl Erem",
                            IsDeleted = false,
                            LastName = "Batuk",
                            TelephoneNumber = "544 516 36 53"
                        },
                        new
                        {
                            Id = 40,
                            CreatedDateTime = new DateTime(2023, 11, 7, 22, 48, 55, 482, DateTimeKind.Local).AddTicks(2769),
                            CreatedUserId = 1,
                            FirstName = "Bensu",
                            IsDeleted = false,
                            LastName = "Batur",
                            TelephoneNumber = "535 674 70 29"
                        },
                        new
                        {
                            Id = 41,
                            CreatedDateTime = new DateTime(2023, 10, 28, 9, 19, 33, 296, DateTimeKind.Local).AddTicks(1551),
                            CreatedUserId = 2,
                            FirstName = "Nazım Orhun",
                            IsDeleted = false,
                            LastName = "Baturalp",
                            TelephoneNumber = "531 312 46 21"
                        },
                        new
                        {
                            Id = 42,
                            CreatedDateTime = new DateTime(2022, 12, 29, 2, 49, 48, 672, DateTimeKind.Local).AddTicks(1816),
                            CreatedUserId = 1,
                            FirstName = "Safa Ahmet",
                            IsDeleted = false,
                            LastName = "Baydar",
                            TelephoneNumber = "537 852 43 40"
                        },
                        new
                        {
                            Id = 43,
                            CreatedDateTime = new DateTime(2023, 7, 18, 11, 5, 50, 127, DateTimeKind.Local).AddTicks(4991),
                            CreatedUserId = 2,
                            FirstName = "Demircan",
                            IsDeleted = false,
                            LastName = "Baydil",
                            TelephoneNumber = "549 529 62 20"
                        },
                        new
                        {
                            Id = 44,
                            CreatedDateTime = new DateTime(2023, 10, 12, 20, 20, 22, 754, DateTimeKind.Local).AddTicks(2227),
                            CreatedUserId = 1,
                            FirstName = "Burçin Kübra",
                            IsDeleted = false,
                            LastName = "Baykal",
                            TelephoneNumber = "534 764 50 69"
                        },
                        new
                        {
                            Id = 45,
                            CreatedDateTime = new DateTime(2023, 12, 2, 2, 53, 37, 290, DateTimeKind.Local).AddTicks(8780),
                            CreatedUserId = 2,
                            FirstName = "Derviş Haluk",
                            IsDeleted = false,
                            LastName = "Baykan",
                            TelephoneNumber = "534 289 24 66"
                        },
                        new
                        {
                            Id = 46,
                            CreatedDateTime = new DateTime(2023, 6, 25, 7, 16, 38, 274, DateTimeKind.Local).AddTicks(6444),
                            CreatedUserId = 1,
                            FirstName = "Taylan Remzi",
                            IsDeleted = false,
                            LastName = "Baykuş",
                            TelephoneNumber = "542 390 50 23"
                        },
                        new
                        {
                            Id = 47,
                            CreatedDateTime = new DateTime(2023, 6, 9, 12, 14, 19, 405, DateTimeKind.Local).AddTicks(8043),
                            CreatedUserId = 2,
                            FirstName = "Abdulvahap",
                            IsDeleted = false,
                            LastName = "Bayrakoğlu",
                            TelephoneNumber = "545 158 79 99"
                        },
                        new
                        {
                            Id = 48,
                            CreatedDateTime = new DateTime(2023, 11, 5, 8, 43, 47, 325, DateTimeKind.Local).AddTicks(4644),
                            CreatedUserId = 1,
                            FirstName = "Aygün",
                            IsDeleted = false,
                            LastName = "Bayram",
                            TelephoneNumber = "545 727 84 03"
                        },
                        new
                        {
                            Id = 49,
                            CreatedDateTime = new DateTime(2023, 6, 2, 22, 35, 51, 79, DateTimeKind.Local).AddTicks(165),
                            CreatedUserId = 2,
                            FirstName = "Ayla",
                            IsDeleted = false,
                            LastName = "Baytın",
                            TelephoneNumber = "530 440 20 78"
                        },
                        new
                        {
                            Id = 50,
                            CreatedDateTime = new DateTime(2023, 4, 27, 10, 53, 50, 139, DateTimeKind.Local).AddTicks(8180),
                            CreatedUserId = 1,
                            FirstName = "Kubilay Barış",
                            IsDeleted = false,
                            LastName = "Begiç",
                            TelephoneNumber = "544 265 58 89"
                        },
                        new
                        {
                            Id = 51,
                            CreatedDateTime = new DateTime(2023, 9, 11, 14, 39, 32, 356, DateTimeKind.Local).AddTicks(2707),
                            CreatedUserId = 2,
                            FirstName = "Mustafa Samed",
                            IsDeleted = false,
                            LastName = "Beğenilmiş",
                            TelephoneNumber = "550 995 95 74"
                        },
                        new
                        {
                            Id = 52,
                            CreatedDateTime = new DateTime(2023, 6, 29, 0, 21, 15, 71, DateTimeKind.Local).AddTicks(4861),
                            CreatedUserId = 1,
                            FirstName = "Berfin Dilay",
                            IsDeleted = false,
                            LastName = "Bekaroğlu",
                            TelephoneNumber = "531 574 09 65"
                        },
                        new
                        {
                            Id = 53,
                            CreatedDateTime = new DateTime(2022, 12, 30, 23, 41, 56, 382, DateTimeKind.Local).AddTicks(493),
                            CreatedUserId = 2,
                            FirstName = "İbrahim Onat",
                            IsDeleted = false,
                            LastName = "Belge",
                            TelephoneNumber = "533 332 03 27"
                        },
                        new
                        {
                            Id = 54,
                            CreatedDateTime = new DateTime(2023, 9, 18, 17, 22, 7, 597, DateTimeKind.Local).AddTicks(8363),
                            CreatedUserId = 1,
                            FirstName = "Jutenya",
                            IsDeleted = false,
                            LastName = "Benan",
                            TelephoneNumber = "542 747 47 85"
                        },
                        new
                        {
                            Id = 55,
                            CreatedDateTime = new DateTime(2023, 1, 26, 6, 44, 36, 940, DateTimeKind.Local).AddTicks(9473),
                            CreatedUserId = 2,
                            FirstName = "Hulki",
                            IsDeleted = false,
                            LastName = "Bent",
                            TelephoneNumber = "549 216 83 63"
                        },
                        new
                        {
                            Id = 56,
                            CreatedDateTime = new DateTime(2023, 12, 1, 3, 22, 52, 519, DateTimeKind.Local).AddTicks(6295),
                            CreatedUserId = 1,
                            FirstName = "Mustafa Doğukan",
                            IsDeleted = false,
                            LastName = "Berberoğlu",
                            TelephoneNumber = "550 548 49 02"
                        },
                        new
                        {
                            Id = 57,
                            CreatedDateTime = new DateTime(2023, 2, 11, 23, 53, 11, 186, DateTimeKind.Local).AddTicks(9842),
                            CreatedUserId = 2,
                            FirstName = "Hüner",
                            IsDeleted = false,
                            LastName = "Berk",
                            TelephoneNumber = "536 639 35 15"
                        },
                        new
                        {
                            Id = 58,
                            CreatedDateTime = new DateTime(2023, 11, 15, 7, 48, 16, 711, DateTimeKind.Local).AddTicks(1614),
                            CreatedUserId = 1,
                            FirstName = "Buse Gizem",
                            IsDeleted = false,
                            LastName = "Berker",
                            TelephoneNumber = "540 624 28 83"
                        },
                        new
                        {
                            Id = 59,
                            CreatedDateTime = new DateTime(2023, 7, 25, 5, 49, 22, 697, DateTimeKind.Local).AddTicks(5526),
                            CreatedUserId = 2,
                            FirstName = "Halime",
                            IsDeleted = false,
                            LastName = "Beydağ",
                            TelephoneNumber = "536 943 36 92"
                        },
                        new
                        {
                            Id = 60,
                            CreatedDateTime = new DateTime(2023, 9, 24, 18, 41, 33, 351, DateTimeKind.Local).AddTicks(5623),
                            CreatedUserId = 1,
                            FirstName = "Didem",
                            IsDeleted = false,
                            LastName = "Bıçaksız",
                            TelephoneNumber = "530 685 14 47"
                        },
                        new
                        {
                            Id = 61,
                            CreatedDateTime = new DateTime(2023, 10, 28, 0, 3, 36, 820, DateTimeKind.Local).AddTicks(7693),
                            CreatedUserId = 2,
                            FirstName = "Mihrinaz",
                            IsDeleted = false,
                            LastName = "Bilal",
                            TelephoneNumber = "549 834 17 73"
                        },
                        new
                        {
                            Id = 62,
                            CreatedDateTime = new DateTime(2023, 2, 24, 9, 13, 31, 566, DateTimeKind.Local).AddTicks(7265),
                            CreatedUserId = 1,
                            FirstName = "Lal",
                            IsDeleted = false,
                            LastName = "Bilgeç",
                            TelephoneNumber = "544 208 71 72"
                        },
                        new
                        {
                            Id = 63,
                            CreatedDateTime = new DateTime(2023, 5, 11, 21, 59, 54, 166, DateTimeKind.Local).AddTicks(6547),
                            CreatedUserId = 2,
                            FirstName = "Senay",
                            IsDeleted = false,
                            LastName = "Bilgen",
                            TelephoneNumber = "542 746 00 01"
                        },
                        new
                        {
                            Id = 64,
                            CreatedDateTime = new DateTime(2023, 4, 14, 7, 43, 26, 452, DateTimeKind.Local).AddTicks(520),
                            CreatedUserId = 1,
                            FirstName = "Remzi",
                            IsDeleted = false,
                            LastName = "Bilgi",
                            TelephoneNumber = "533 968 21 11"
                        },
                        new
                        {
                            Id = 65,
                            CreatedDateTime = new DateTime(2023, 7, 16, 21, 3, 3, 670, DateTimeKind.Local).AddTicks(5490),
                            CreatedUserId = 2,
                            FirstName = "Armağan",
                            IsDeleted = false,
                            LastName = "Bilgiç",
                            TelephoneNumber = "539 302 07 98"
                        },
                        new
                        {
                            Id = 66,
                            CreatedDateTime = new DateTime(2023, 1, 18, 12, 58, 3, 865, DateTimeKind.Local).AddTicks(3165),
                            CreatedUserId = 1,
                            FirstName = "Çelik",
                            IsDeleted = false,
                            LastName = "Bilgir",
                            TelephoneNumber = "536 104 98 52"
                        },
                        new
                        {
                            Id = 67,
                            CreatedDateTime = new DateTime(2023, 9, 18, 21, 1, 21, 231, DateTimeKind.Local).AddTicks(5712),
                            CreatedUserId = 2,
                            FirstName = "Kübra Tansu",
                            IsDeleted = false,
                            LastName = "Bilgit",
                            TelephoneNumber = "535 579 23 59"
                        },
                        new
                        {
                            Id = 68,
                            CreatedDateTime = new DateTime(2023, 3, 17, 18, 26, 41, 955, DateTimeKind.Local).AddTicks(940),
                            CreatedUserId = 1,
                            FirstName = "Uluç Emre",
                            IsDeleted = false,
                            LastName = "Binbay",
                            TelephoneNumber = "542 236 28 01"
                        },
                        new
                        {
                            Id = 69,
                            CreatedDateTime = new DateTime(2023, 12, 1, 15, 2, 4, 619, DateTimeKind.Local).AddTicks(8932),
                            CreatedUserId = 2,
                            FirstName = "Mehmet Buğrahan",
                            IsDeleted = false,
                            LastName = "Birgili",
                            TelephoneNumber = "536 151 20 22"
                        },
                        new
                        {
                            Id = 70,
                            CreatedDateTime = new DateTime(2023, 1, 19, 2, 50, 53, 602, DateTimeKind.Local).AddTicks(2337),
                            CreatedUserId = 1,
                            FirstName = "Doğuşcan",
                            IsDeleted = false,
                            LastName = "Biriz",
                            TelephoneNumber = "534 619 87 78"
                        },
                        new
                        {
                            Id = 71,
                            CreatedDateTime = new DateTime(2023, 1, 6, 2, 22, 48, 528, DateTimeKind.Local).AddTicks(2069),
                            CreatedUserId = 2,
                            FirstName = "Altan",
                            IsDeleted = false,
                            LastName = "Boy",
                            TelephoneNumber = "533 333 03 12"
                        },
                        new
                        {
                            Id = 72,
                            CreatedDateTime = new DateTime(2023, 10, 19, 20, 11, 13, 413, DateTimeKind.Local).AddTicks(9627),
                            CreatedUserId = 1,
                            FirstName = "Bengisu",
                            IsDeleted = false,
                            LastName = "Boya",
                            TelephoneNumber = "530 293 40 63"
                        },
                        new
                        {
                            Id = 73,
                            CreatedDateTime = new DateTime(2023, 5, 11, 22, 27, 48, 53, DateTimeKind.Local).AddTicks(4239),
                            CreatedUserId = 2,
                            FirstName = "Onur Taylan",
                            IsDeleted = false,
                            LastName = "Boylu",
                            TelephoneNumber = "539 405 50 93"
                        },
                        new
                        {
                            Id = 74,
                            CreatedDateTime = new DateTime(2023, 5, 17, 16, 23, 13, 188, DateTimeKind.Local).AddTicks(3128),
                            CreatedUserId = 1,
                            FirstName = "Ayseren",
                            IsDeleted = false,
                            LastName = "Boyuktaş",
                            TelephoneNumber = "536 574 07 33"
                        },
                        new
                        {
                            Id = 75,
                            CreatedDateTime = new DateTime(2023, 12, 15, 0, 57, 53, 913, DateTimeKind.Local).AddTicks(4478),
                            CreatedUserId = 2,
                            FirstName = "Pekin",
                            IsDeleted = false,
                            LastName = "Boz",
                            TelephoneNumber = "532 580 25 65"
                        },
                        new
                        {
                            Id = 76,
                            CreatedDateTime = new DateTime(2023, 4, 1, 2, 56, 38, 735, DateTimeKind.Local).AddTicks(6845),
                            CreatedUserId = 1,
                            FirstName = "Aksu",
                            IsDeleted = false,
                            LastName = "Bozdağ",
                            TelephoneNumber = "533 403 07 56"
                        },
                        new
                        {
                            Id = 77,
                            CreatedDateTime = new DateTime(2023, 10, 25, 10, 34, 5, 689, DateTimeKind.Local).AddTicks(5562),
                            CreatedUserId = 2,
                            FirstName = "Arkan",
                            IsDeleted = false,
                            LastName = "Bozdemir",
                            TelephoneNumber = "543 358 64 18"
                        },
                        new
                        {
                            Id = 78,
                            CreatedDateTime = new DateTime(2023, 6, 18, 21, 1, 7, 173, DateTimeKind.Local).AddTicks(7024),
                            CreatedUserId = 1,
                            FirstName = "İltem",
                            IsDeleted = false,
                            LastName = "Boztepe",
                            TelephoneNumber = "533 293 16 26"
                        },
                        new
                        {
                            Id = 79,
                            CreatedDateTime = new DateTime(2023, 3, 8, 6, 12, 16, 821, DateTimeKind.Local).AddTicks(19),
                            CreatedUserId = 2,
                            FirstName = "Betül",
                            IsDeleted = false,
                            LastName = "Bozyer",
                            TelephoneNumber = "536 334 16 76"
                        },
                        new
                        {
                            Id = 80,
                            CreatedDateTime = new DateTime(2023, 9, 1, 8, 52, 46, 626, DateTimeKind.Local).AddTicks(9919),
                            CreatedUserId = 1,
                            FirstName = "Ogün",
                            IsDeleted = false,
                            LastName = "Bölge",
                            TelephoneNumber = "532 482 54 94"
                        },
                        new
                        {
                            Id = 81,
                            CreatedDateTime = new DateTime(2023, 3, 22, 5, 56, 58, 11, DateTimeKind.Local).AddTicks(1371),
                            CreatedUserId = 2,
                            FirstName = "İbrahim Hakkı",
                            IsDeleted = false,
                            LastName = "Bugey",
                            TelephoneNumber = "544 685 12 54"
                        },
                        new
                        {
                            Id = 82,
                            CreatedDateTime = new DateTime(2023, 2, 4, 12, 29, 35, 269, DateTimeKind.Local).AddTicks(6651),
                            CreatedUserId = 1,
                            FirstName = "Onay",
                            IsDeleted = false,
                            LastName = "Buğdaypınarı",
                            TelephoneNumber = "543 801 65 88"
                        },
                        new
                        {
                            Id = 83,
                            CreatedDateTime = new DateTime(2023, 4, 1, 4, 59, 42, 786, DateTimeKind.Local).AddTicks(4921),
                            CreatedUserId = 2,
                            FirstName = "Cankız",
                            IsDeleted = false,
                            LastName = "Bulgan",
                            TelephoneNumber = "540 709 31 78"
                        },
                        new
                        {
                            Id = 84,
                            CreatedDateTime = new DateTime(2023, 6, 19, 17, 2, 36, 285, DateTimeKind.Local).AddTicks(6850),
                            CreatedUserId = 1,
                            FirstName = "Arzucan",
                            IsDeleted = false,
                            LastName = "Bulgur",
                            TelephoneNumber = "545 755 10 25"
                        },
                        new
                        {
                            Id = 85,
                            CreatedDateTime = new DateTime(2023, 9, 19, 14, 51, 37, 557, DateTimeKind.Local).AddTicks(1515),
                            CreatedUserId = 2,
                            FirstName = "Asiye",
                            IsDeleted = false,
                            LastName = "Burabak",
                            TelephoneNumber = "538 179 64 18"
                        },
                        new
                        {
                            Id = 86,
                            CreatedDateTime = new DateTime(2023, 2, 6, 11, 25, 34, 371, DateTimeKind.Local).AddTicks(333),
                            CreatedUserId = 1,
                            FirstName = "Ahmet Yasin",
                            IsDeleted = false,
                            LastName = "Burak",
                            TelephoneNumber = "533 297 90 13"
                        },
                        new
                        {
                            Id = 87,
                            CreatedDateTime = new DateTime(2023, 12, 2, 0, 51, 44, 404, DateTimeKind.Local).AddTicks(6117),
                            CreatedUserId = 2,
                            FirstName = "Yaprak",
                            IsDeleted = false,
                            LastName = "Bural",
                            TelephoneNumber = "540 795 56 87"
                        },
                        new
                        {
                            Id = 88,
                            CreatedDateTime = new DateTime(2023, 1, 4, 8, 19, 52, 99, DateTimeKind.Local).AddTicks(533),
                            CreatedUserId = 1,
                            FirstName = "Aleda",
                            IsDeleted = false,
                            LastName = "Buyuran",
                            TelephoneNumber = "534 733 25 66"
                        },
                        new
                        {
                            Id = 89,
                            CreatedDateTime = new DateTime(2023, 12, 5, 0, 17, 26, 633, DateTimeKind.Local).AddTicks(3474),
                            CreatedUserId = 2,
                            FirstName = "Can Güney",
                            IsDeleted = false,
                            LastName = "Bülbül",
                            TelephoneNumber = "533 814 96 96"
                        },
                        new
                        {
                            Id = 90,
                            CreatedDateTime = new DateTime(2023, 3, 30, 19, 33, 51, 327, DateTimeKind.Local).AddTicks(5269),
                            CreatedUserId = 1,
                            FirstName = "Mahmut Bilal",
                            IsDeleted = false,
                            LastName = "Bülend",
                            TelephoneNumber = "542 874 20 58"
                        },
                        new
                        {
                            Id = 91,
                            CreatedDateTime = new DateTime(2023, 3, 5, 18, 1, 22, 770, DateTimeKind.Local).AddTicks(3343),
                            CreatedUserId = 2,
                            FirstName = "Saliha Zeynep",
                            IsDeleted = false,
                            LastName = "Bülent",
                            TelephoneNumber = "534 561 97 07"
                        },
                        new
                        {
                            Id = 92,
                            CreatedDateTime = new DateTime(2023, 6, 5, 5, 56, 6, 825, DateTimeKind.Local).AddTicks(9091),
                            CreatedUserId = 1,
                            FirstName = "Melike Dilara",
                            IsDeleted = false,
                            LastName = "Büyükfırat",
                            TelephoneNumber = "546 822 76 87"
                        },
                        new
                        {
                            Id = 93,
                            CreatedDateTime = new DateTime(2023, 10, 23, 12, 35, 53, 271, DateTimeKind.Local).AddTicks(7595),
                            CreatedUserId = 2,
                            FirstName = "Hayriye",
                            IsDeleted = false,
                            LastName = "Büyükgüngör",
                            TelephoneNumber = "539 525 22 11"
                        },
                        new
                        {
                            Id = 94,
                            CreatedDateTime = new DateTime(2023, 3, 3, 13, 8, 1, 781, DateTimeKind.Local).AddTicks(7237),
                            CreatedUserId = 1,
                            FirstName = "Sebiha",
                            IsDeleted = false,
                            LastName = "Büyüköztürk",
                            TelephoneNumber = "550 776 86 64"
                        },
                        new
                        {
                            Id = 95,
                            CreatedDateTime = new DateTime(2023, 8, 31, 11, 26, 49, 664, DateTimeKind.Local).AddTicks(2023),
                            CreatedUserId = 2,
                            FirstName = "Mehmet",
                            IsDeleted = false,
                            LastName = "Can Akçaözoğlu",
                            TelephoneNumber = "539 495 27 54"
                        },
                        new
                        {
                            Id = 96,
                            CreatedDateTime = new DateTime(2023, 12, 7, 10, 14, 18, 492, DateTimeKind.Local).AddTicks(203),
                            CreatedUserId = 1,
                            FirstName = "Mehmet Enes",
                            IsDeleted = false,
                            LastName = "Canan",
                            TelephoneNumber = "534 704 24 01"
                        },
                        new
                        {
                            Id = 97,
                            CreatedDateTime = new DateTime(2023, 6, 30, 2, 4, 59, 809, DateTimeKind.Local).AddTicks(5162),
                            CreatedUserId = 2,
                            FirstName = "Kurtbey",
                            IsDeleted = false,
                            LastName = "Canbağı",
                            TelephoneNumber = "533 498 43 45"
                        },
                        new
                        {
                            Id = 98,
                            CreatedDateTime = new DateTime(2023, 12, 5, 22, 54, 58, 677, DateTimeKind.Local).AddTicks(6057),
                            CreatedUserId = 1,
                            FirstName = "Mustafa Taha",
                            IsDeleted = false,
                            LastName = "Canbek",
                            TelephoneNumber = "538 438 54 10"
                        },
                        new
                        {
                            Id = 99,
                            CreatedDateTime = new DateTime(2023, 6, 7, 9, 25, 45, 162, DateTimeKind.Local).AddTicks(2004),
                            CreatedUserId = 2,
                            FirstName = "Sena Nur",
                            IsDeleted = false,
                            LastName = "Candan",
                            TelephoneNumber = "543 417 93 21"
                        },
                        new
                        {
                            Id = 100,
                            CreatedDateTime = new DateTime(2023, 1, 30, 22, 49, 34, 775, DateTimeKind.Local).AddTicks(2405),
                            CreatedUserId = 1,
                            FirstName = "Abdullah Emirhan",
                            IsDeleted = false,
                            LastName = "Caner",
                            TelephoneNumber = "549 113 83 96"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("OrionPos.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("OrionPos.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrionPos.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("OrionPos.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrionPos.Entity.Entities.TelephoneDirectory", b =>
                {
                    b.HasOne("OrionPos.Entity.Entities.AppUser", "CreatedUser")
                        .WithMany("TelephoneDirectories")
                        .HasForeignKey("CreatedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("OrionPos.Entity.Entities.AppUser", b =>
                {
                    b.Navigation("TelephoneDirectories");
                });
#pragma warning restore 612, 618
        }
    }
}
